const std = @import("std");
const testing = std.testing;
const ingestion = @import("ingestion");
const mtx = ingestion.transcriptomics.mtx;

// ─── Happy Path ───────────────────────────────────────────────────────────────

test "mtx: parse valid 2x2 sparse matrix" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "% comment\n" ++
        "2 2 2\n" ++
        "1 1 1.0\n" ++
        "2 2 2.0\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    var sparse = try parser.parseSparseMmap(data);
    defer sparse.deinit();
    try testing.expectEqual(@as(usize, 2), sparse.rows);
    try testing.expectEqual(@as(usize, 2), sparse.cols);
    try testing.expectEqual(@as(f64, 1.0), sparse.data[0]);
    try testing.expectEqual(@as(f64, 2.0), sparse.data[1]);
}

test "mtx: indptr boundaries are correct for single-col matrix" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "3 1 3\n" ++
        "1 1 10.0\n" ++
        "2 1 20.0\n" ++
        "3 1 30.0\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    var sparse = try parser.parseSparseMmap(data);
    defer sparse.deinit();
    // Every row has exactly 1 entry: indptr = [0,1,2,3]
    try testing.expectEqual(@as(u32, 0), sparse.indptr[0]);
    try testing.expectEqual(@as(u32, 1), sparse.indptr[1]);
    try testing.expectEqual(@as(u32, 2), sparse.indptr[2]);
    try testing.expectEqual(@as(u32, 3), sparse.indptr[3]);
}

test "mtx: comment-only lines after header are skipped" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "% generated by test\n" ++
        "% another comment\n" ++
        "2 2 1\n" ++
        "1 1 5.5\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    var sparse = try parser.parseSparseMmap(data);
    defer sparse.deinit();
    try testing.expectEqual(@as(f64, 5.5), sparse.data[0]);
}

// ─── Header Validation ────────────────────────────────────────────────────────

test "mtx: missing MatrixMarket header" {
    const data = "2 2 1\n1 1 1.0\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxHeaderMissing, parser.parseSparseMmap(data));
}

test "mtx: unsupported format (integer instead of real)" {
    const data =
        "%%MatrixMarket matrix coordinate integer general\n" ++
        "2 2 1\n1 1 1\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.UnsupportedMtxFormat, parser.parseSparseMmap(data));
}

test "mtx: missing rows dimension line" {
    const data = "%%MatrixMarket matrix coordinate real general\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxMissingRows, parser.parseSparseMmap(data));
}

test "mtx: missing cols in dimension line" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "3\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxMissingCols, parser.parseSparseMmap(data));
}

test "mtx: zero rows declared (invalid dimensions)" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "0 5 0\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.InvalidMtxDimensions, parser.parseSparseMmap(data));
}

// ─── Data Integrity ───────────────────────────────────────────────────────────

test "mtx: entry count mismatch (fewer entries than declared)" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "3 3 5\n" ++
        "1 1 1.0\n" ++  // only 1 entry but declared 5
        "\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxEntryCountMismatch, parser.parseSparseMmap(data));
}

test "mtx: row index out of bounds (row > declared rows)" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "2 2 1\n" ++
        "5 1 1.0\n"; // row 5 declared but only 2 rows exist
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxIndexOutOfBounds, parser.parseSparseMmap(data));
}

test "mtx: col index out of bounds (col > declared cols)" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "2 2 1\n" ++
        "1 9 1.0\n"; // col 9 when only 2 cols declared
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxIndexOutOfBounds, parser.parseSparseMmap(data));
}

test "mtx: row index = 0 is invalid (MTX is 1-based)" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "2 2 1\n" ++
        "0 1 1.0\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    try testing.expectError(error.MtxIndexOutOfBounds, parser.parseSparseMmap(data));
}

// ─── Sparse -> Dense Conversion ───────────────────────────────────────────────

test "mtx: parseDenseMmap produces correct dense matrix from sparse" {
    const data =
        "%%MatrixMarket matrix coordinate real general\n" ++
        "2 2 2\n" ++
        "1 1 3.0\n" ++
        "2 2 7.0\n";
    const parser = mtx.MtxParser.init(testing.allocator);
    var dense = try parser.parseDenseMmap(data);
    defer dense.deinit();
    try testing.expectEqual(@as(f64, 3.0), dense.get(0, 0));
    try testing.expectEqual(@as(f64, 0.0), dense.get(0, 1));
    try testing.expectEqual(@as(f64, 0.0), dense.get(1, 0));
    try testing.expectEqual(@as(f64, 7.0), dense.get(1, 1));
}
